apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db-secret
  namespace: devops-lab
type: Opaque
stringData:
  POSTGRES_URL: "jdbc:postgresql://pg-petclinic-server-silarac.postgres.database.azure.com:5432/petclinic?sslmode=require"
  POSTGRES_USER: "petclinicadmin"
  POSTGRES_PASS: "G9R+gL90jm"