apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db-secret
  namespace: devops-lab
type: Opaque
stringData:
  # La URL usará el formato de Azure. Reemplaza <TU_DB_NAME> con el nombre que pusiste en variables.tf
  POSTGRES_URL: "jdbc:postgresql://<pg-petclinic-server-silarac>.postgres.database.azure.com:5432/petclinic?sslmode=require"
  POSTGRES_USER: "petclinicadmin"
  POSTGRES_PASS: "<G9R+gL90jm>" # La misma que pusiste en los secretos de GitHub

