apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db-secret
  namespace: devops-lab
type: Opaque
stringData:
  POSTGRES_URL: "jdbc:postgresql://CLOUD_SQL_IP:5432/petclinic"
  POSTGRES_USER: "petclinicadmin"
  POSTGRES_PASS: "DB_PASSWORD_PLACEHOLDER"