apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: petclinic-pdb
  namespace: devops-lab
spec:
  minAvailable: 1 # Siempre debe haber al menos 1 pod vivo durante mantenimientos
  selector:
    matchLabels:
      app: petclinic