apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: devops-lab
spec:
  type: LoadBalancer # Esto le pedirá a GCP una IP Pública
  selector:
    app: petclinic
  ports:
  - name: http
    port: 80
    targetPort: 8080