apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: devops-lab
spec:
  type: LoadBalancer # Esto le pedirá a Azure una IP Pública
  selector:
    app: petclinic
  ports:
  - port: 80
    targetPort: 8080