name: CI/CD Pipeline - Spring PetClinic (Railway)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    name: Build, Test & SAST
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # --- PASO DEVSECOPS: ESCANEO DE SECRETOS ---
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Compile and Run Unit Tests with Maven
      run: |
        cd app
        mvn clean verify

    # --- PASO DEVSECOPS: ANÁLISIS ESTÁTICO DE CALIDAD ---
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: app
        args: >
          -Dsonar.projectKey=StevenISMAEL_PetClinic-devops2
          -Dsonar.organization=stevenismael
          -Dsonar.qualitygate.wait=true
          -Dsonar.java.binaries=target/classes

  docker-build:
    name: Containerize & Security Scan
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # --- PASO DEVSECOPS: ESCANEO DE VULNERABILIDADES (TRIVY) ---
    - name: Build local image for security scan
      run: |
        docker build -t petclinic:test ./app

    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'petclinic:test'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL'

    - name: Convert repository name to lowercase
      run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Image to GHCR
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        tags: |
          ghcr.io/${{ env.REPO_LC }}/petclinic:latest
          ghcr.io/${{ env.REPO_LC }}/petclinic:${{ github.sha }}
# --- PASO CD: DESPLIEGUE CONTINUO A RENDER ---
  deploy-production:
    name: Deploy to Render
    needs: docker-build
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Render Deployment
      run: |
        echo "Activando el despliegue en Render..."
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
        echo "Despliegue iniciado exitosamente."